### ISSUE TITLE
[LMS Admin] #2 informacja ze cena w groszach...

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#108]
informacja ze cena w groszach/centach

*Source url:* https://escolalms.github.io/Admin/#/Admin/courses/6
*Reported by:* mateusz@escolasoft.com
*Reported at:* 13 Sep at 09:08 UTC

*Console:* [1× Error](https://ybug.io/dashboard/reports/detail/q9pg2cj327rj2py5bkw1#console)

*Location:* PL, Pomerania, Gdansk
*Browser:* Chrome 93.0.4577.63

*OS:* macOS 10.15.7
*Screen:* 1920x1080
*Viewport:* 1920x887

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/b307ykjnw50dx3pg1r2y/q9pg2cj327rj2py5bkw1/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MzE1MjQxNDEsImRhdGEiOnsicmVwb3J0IjoicTlwZzJjajMyN3JqMnB5NWJrdzEiLCJ1c2VyIjoiR2l0SHViIn19.FL9a0wZl8oNd3cC2SHVNaXIk1eM09Hd1BURPKnMzK_o)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/q9pg2cj327rj2py5bkw1](https://ybug.io/dashboard/reports/detail/q9pg2cj327rj2py5bkw1)

**Comment by qunabu** [comment]
add tooltip or any other explicit info that this price is in cents

**Comment by dawidzebacki** [comment]
https://github.com/EscolaLMS/Admin/pull/129
