### ISSUE TITLE
[LMS Admin] #5 nie działaja raporty

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#111]
nie działaja raporty

*Source url:* https://escolalms.github.io/Admin/#/Admin/reports
*Reported by:* mateusz@escolasoft.com
*Reported at:* 13 Sep at 09:27 UTC

*Console:* [5× Error, 8× Log](https://ybug.io/dashboard/reports/detail/j6yb6d4cyd3s4d4ck6pn#console)

*Location:* PL, Pomerania, Gdansk
*Browser:* Chrome 93.0.4577.63

*OS:* macOS 10.15.7
*Screen:* 1920x1080
*Viewport:* 1920x887

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/b307ykjnw50dx3pg1r2y/j6yb6d4cyd3s4d4ck6pn/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MzE1MjUyMzQsImRhdGEiOnsicmVwb3J0IjoiajZ5YjZkNGN5ZDNzNGQ0Y2s2cG4iLCJ1c2VyIjoiR2l0SHViIn19.dknkMhZpjNPjGYmLLJVI5rqTZksOkEQY6m3mQzky0Fs)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/j6yb6d4cyd3s4d4ck6pn](https://ybug.io/dashboard/reports/detail/j6yb6d4cyd3s4d4ck6pn)

**Comment by pa-cholek** [comment]
This should be fixed in latest Reports release
