### ISSUE TITLE
poster w course 

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#113]
api allows to send a poster next to video - gui is missing this option 

should be implemented with "secureupload" component https://github.com/EscolaLMS/Admin/tree/master/src/components/SecureUpload

<img width="1176" alt="Screenshot 2021-09-15 at 21 27 48" src="https://user-images.githubusercontent.com/214608/133497156-ccb1148f-e319-48c6-b7eb-8d14d43b830b.png">

**Comment by dawidzebacki** [comment]
https://github.com/EscolaLMS/Admin/pull/130
