### ISSUE TITLE
tutor can't edit courses

### ISSUE THREAD

**Issue by dawidzebacki** [EscolaLMS/Admin#126]
![Zrzut ekranu z 2021-09-15 14-05-00](https://user-images.githubusercontent.com/64470068/133430174-845954de-ea7c-48ab-904e-120f791b6c56.png)

Logged as tutor when i want to edit some course there is an error: 

![Zrzut ekranu z 2021-09-15 10-55-50](https://user-images.githubusercontent.com/64470068/133429843-030c0886-5136-4d65-8cb5-35c04ab6983b.png)

After creating new course this course is changing address to: `/courses/id/attributes` and there is also an error even if course has beed created succesfully. Deleting is working properly.

**Comment by qunabu** [comment]
tutor should be able to do whatever with his project

**Comment by pa-cholek** [comment]
This error is about `GET /api/admin/users/{id}` endpoint; I'm not sure if tutors should have permission to read this endpoint for users that are subscribed to their courses?

**Comment by pa-cholek** [comment]
Fixed in https://github.com/EscolaLMS/Auth/releases/tag/0.1.37
