### ISSUE TITLE
i cant set active lesson

### ISSUE THREAD

**Issue by victazzz** [EscolaLMS/Admin#131]
curl 'https://escola-lms-api.stage.etd24.pl/api/admin/lessons/28?_method=PUT' \
      -H 'authority: escola-lms-api.stage.etd24.pl' \
      -H 'pragma: no-cache' \
      -H 'cache-control: no-cache' \
      -H 'sec-ch-ua: "Google Chrome";v="93", " Not;A Brand";v="99", "Chromium";v="93"' \
      -H 'accept: application/json' \
      -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundaryAPP19hbs0u393edl' \
      -H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5NDY1NGU3MS05ZWI5LTQxYjEtOWU1OS05YjQ3YzQ5OTczYWQiLCJqdGkiOiIzOWVhMGEwYWNhMWNlOWE1NDIzOWZjMzhiMGZlZmIwOWJmMjZmMmE5YzkzYjQwODRiMTY4ZTA1MjMzOWQxMjA5MDEyZGFhOGY4YWM5YjNiOSIsImlhdCI6MTYzMTY4NTYwNy4yMTQwNjcsIm5iZiI6MTYzMTY4NTYwNy4yMTQwNzcsImV4cCI6MTY2MzIyMTYwNy4yMTE2MjIsInN1YiI6IjIiLCJzY29wZXMiOltdfQ.crhSmpBdwIUqEX6jnejcnV4ZUbBlrkNiopbCW7x_eaUXJN0LOr0qqA8_XkW4uOWHDAdFeN9u8K4NiyKmfSXmGW-9g4UQXPKFI8WI1w6zqN1EdMRXkpMF0bD3PgSaG_oiVBZEQnIKVbogeVmUta1epLkdOZxLX4WuMRaFZjO11oBLVqPb4fvL2wSYIGlhkaIQizJQkdbUHEuV_rHlGLgyrlP3uQ3At5_sKDEJMDanAO_4-G-eivWVPjE8YE4oBswMRRfAjxAmjH5Fsa4obs0Xv-L5sjc7FcfvQ0G1lSj3CucJHHVOLy69yW3ymjPOrjPRDrjsHLiIxL5LesXTY1ZxsuV0Z70vaPVHqegrBOmIQtEHfaBhyZnUNw4JeNqCvec6dTa9oeO3WuRPZnPmhNKF2eRDNjuVd0yRpaZvwCBmpEQpBFVf7PwLtTx2RXutNB8OBXzsZaqfN3YSJaVP_TumfZ-UDN-egjVOgCXajscSM_XZ9MCs3leZkp_cDkCJaQlzGBewWJlVUN6CTewGFLe5xKmXXKif-S-GNQkd3pWp2bRes2CTYy_Jgx0pAzmlUxrTwjkeIEx0EnHkZ4hUy8zEi1iOYHzgtUaqC6bpUrtxRbKJDG39O_OSb4p_U_rT9P4N4xKxPEyJesXMhtxdXJEFuFYLX6yuNJjHdFBccDmlSwQ' \
      -H 'sec-ch-ua-mobile: ?0' \
      -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36' \
      -H 'sec-ch-ua-platform: "macOS"' \
      -H 'origin: https://escolalms.github.io' \
      -H 'sec-fetch-site: cross-site' \
      -H 'sec-fetch-mode: cors' \
      -H 'sec-fetch-dest: empty' \
      -H 'referer: https://escolalms.github.io/' \
      -H 'accept-language: pl,en-US;q=0.9,en;q=0.8' \
      --data-raw $'------WebKitFormBoundaryAPP19hbs0u393edl\r\nContent-Disposition: form-data; name="id"\r\n\r\n28\r\n------WebKitFormBoundaryAPP19hbs0u393edl\r\nContent-Disposition: form-data; name="title"\r\n\r\nawdwad\r\n------WebKitFormBoundaryAPP19hbs0u393edl\r\nContent-Disposition: form-data; name="active"\r\n\r\n1\r\n------WebKitFormBoundaryAPP19hbs0u393edl\r\nContent-Disposition: form-data; name="topics"\r\n\r\n[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]\r\n------WebKitFormBoundaryAPP19hbs0u393edl\r\nContent-Disposition: form-data; name="order"\r\n\r\n1\r\n------WebKitFormBoundaryAPP19hbs0u393edl--\r\n' \
      --compressed

_Issue created from a [Mattermost message](https://mattermost.etd24.pl/_redirect/pl/o7mgjj9x5tfbmmech1jwcyg61r) *by @victazzz*._

**Comment by dawidzebacki** [comment]
There was a bug that when you are in some course (tab program) and reload a page then `course.id` was `undefined` and you were not able to update lesson at all. I also added order which is required now. Please check if it works now (for me it's working :P).

Fixed this in issue: https://github.com/EscolaLMS/Admin/issues/135

file changes: https://github.com/EscolaLMS/Admin/pull/139/files#diff-db97473083e2dd8ccf6979d55fe1336a02b36d258b6b8c5c982a02712f77e9e0

@victazzz
