### ISSUE TITLE
when I type a letter in the selection of the h5p element it crash

### ISSUE THREAD

**Issue by victazzz** [EscolaLMS/Admin#132]
when I type a letter in the selection of the h5p element it crashes

_Issue created from a [Mattermost message](https://mattermost.etd24.pl/_redirect/pl/hug36ujmwtnh7pqfuk7xayc8na) *by @victazzz*._

**Comment by qunabu** [comment]
screenshot pliz

**Comment by victazzz** [comment]
![image](https://user-images.githubusercontent.com/24989821/133596504-7387ae04-0d55-453f-8359-a5ed9cc7a8fe.png)
w tym miejscu

![image](https://user-images.githubusercontent.com/24989821/133596549-55af648b-3b40-4cbb-898c-bfa6f55bf3a5.png)

**Comment by dawidzebacki** [comment]
https://github.com/EscolaLMS/Admin/pull/140
