### ISSUE TITLE
single course stats

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#134]
relates to https://github.com/EscolaLMS/Reports/pull/13
use same way stats are renders in overall reports section 
<img width="1153" alt="Screenshot 2021-09-16 at 12 25 00" src="https://user-images.githubusercontent.com/214608/133596626-8c13216a-60fa-426a-9fe6-cd536b360d81.png">

**Comment by dawidzebacki** [comment]
https://github.com/EscolaLMS/Admin/pull/147
