### ISSUE TITLE
set active topic does not work when topic is inactive by default

### ISSUE THREAD

**Issue by victazzz** [EscolaLMS/Admin#149]
curl 'https://escola-lms-api.stage.etd24.pl/api/admin/topics/29?_method=PUT' \
      -H 'authority: escola-lms-api.stage.etd24.pl' \
      -H 'pragma: no-cache' \
      -H 'cache-control: no-cache' \
      -H 'sec-ch-ua: "Google Chrome";v="93", " Not;A Brand";v="99", "Chromium";v="93"' \
      -H 'accept: application/json' \
      -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundaryACNFXVX6hMiTZG61' \
      -H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5NDZiNjM2YS1iZThjLTRhYTEtOTRjMi0yOWZmYTlmNGE5ZDAiLCJqdGkiOiI5Y2RmMTQ1Mzg0MmMzYTQ5MDgxOWY2YTU1YzRhZGVkZDFiNDNiYjU2OGI0ZDFjNmM4YjE4ZjRjODMwODZiOTVjMWQ1MTQyYTQ5MjUzODdkMSIsImlhdCI6MTYzMjExMzY5My45NDA2MDQsIm5iZiI6MTYzMjExMzY5My45NDA2MzYsImV4cCI6MTY2MzY0OTY5My45MzI4ODcsInN1YiI6IjIiLCJzY29wZXMiOltdfQ.K1qgoGWqGPhPeFVBKhUV9XgbtggmJfDLTVff8UBjk2EXuWWA3aOyv9_7hh28Cq_LSZdCvWeyQuo3O7nh9NSGSEK8S05Yamp5MlD2jI8BIRJB8L-eixGhrqHEAlNDw6Ba7WKfAQ3qVWwQCIwE1VYHjLigad-D7dXUBRCs6wnZZgBd_zo1ykQQRTUO3QvLlTGeRtAOliAWBcuuiSyQhsG-moKe8gYDq_PoaKVQAbYoWaCY5B89VDAoot8XIYgATYrftRgdYz2REKatMN3FkLM25h8_y9uX1CXoEwBcPlCJtByzksGGVE7HsGoeVSpgk2I22_uF_-1Md9xS-LpS1U_Z4gDkWpPvt2sgUOgR-ukGasZILh6nPAikP2KcQ9ZbTaDW3ynQ_Tn2sGX1Idz3k965AlvH6v4rtLOJdDicvgPxfGYqwEPdkfFRUhtnralbDYFfbNcmJcSu1u4HBv_493dFL4v-Nd8Fae6uv6JXyOzgaii_r6ZqfUJeAWQNKzsM7rdJ_zWzaRQ-SGe1crJxTkRHEt769kYyKbHLxYH_xEpl0MmFoP2ObkqMchp2recOnJyqpq6ZC4F9MjIWDTMsmM_8aInkzcbH1LaF2MexZQ3tesU5K7bcmPiMcZSYYo4y64aUPtGa7pWvLl5pJmst8MwFeDrKHPxYluIvoUJWxuKbCRE' \
      -H 'sec-ch-ua-mobile: ?0' \
      -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36' \
      -H 'sec-ch-ua-platform: "macOS"' \
      -H 'origin: https://escolalms.github.io' \
      -H 'sec-fetch-site: cross-site' \
      -H 'sec-fetch-mode: cors' \
      -H 'sec-fetch-dest: empty' \
      -H 'referer: https://escolalms.github.io/' \
      -H 'accept-language: pl,en-US;q=0.9,en;q=0.8' \
      --data-raw $'------WebKitFormBoundaryACNFXVX6hMiTZG61\r\nContent-Disposition: form-data; name="id"\r\n\r\n29\r\n------WebKitFormBoundaryACNFXVX6hMiTZG61\r\nContent-Disposition: form-data; name="title"\r\n\r\nconsequatur\r\n------WebKitFormBoundaryACNFXVX6hMiTZG61\r\nContent-Disposition: form-data; name="lesson_id"\r\n\r\n5\r\n------WebKitFormBoundaryACNFXVX6hMiTZG61\r\nContent-Disposition: form-data; name="active"\r\n\r\n1\r\n------WebKitFormBoundaryACNFXVX6hMiTZG61\r\nContent-Disposition: form-data; name="preview"\r\n\r\n1\r\n------WebKitFormBoundaryACNFXVX6hMiTZG61\r\nContent-Disposition: form-data; name="topicable_id"\r\n\r\n9\r\n------WebKitFormBoundaryACNFXVX6hMiTZG61\r\nContent-Disposition: form-data; name="topicable_type"\r\n\r\nEscolaLms\\Courses\\Models\\TopicContent\\PDF\r\n------WebKitFormBoundaryACNFXVX6hMiTZG61\r\nContent-Disposition: form-data; name="topicable"\r\n\r\n[object Object]\r\n------WebKitFormBoundaryACNFXVX6hMiTZG61\r\nContent-Disposition: form-data; name="summary"\r\n\r\n# Velit cupiditate minima mollitia perferendis facere in.\n\n> Culpa minima incidunt voluptas laborum. Dignissimos accusantium magni quasi quis voluptatem nihil autem quae. Tempore occaecati voluptates eos ab modi eos ab.\n\n\n1. Rerum est cumque quos eligendi.\n2. Quia error velit recusandae provident molestias.\n3. Inventore totam sed ab eos nulla quam.\n\n# Sapiente totam similique praesentium dicta quaerat.\n\n* Eligendi veritatis quisquam quia voluptates consectetur quisquam eum.\n* Accusamus et est ducimus tempora.\n* Quas sit doloribus dicta incidunt dolorum dolores eos.\n\n\n1. Nulla dolores neque id ipsa.\n2. Eius quod omnis deserunt exercitationem.\n3. Dicta et voluptas ut consequatur.\n\n# Ullam natus quos qui qui eum consequuntur.\n\nExcepturi aut autem sunt deserunt ex. Aperiam expedita rem nesciunt velit.\n\n* Ut accusamus eos sit perferendis odit.\n* Odio facilis voluptatem odio eveniet.\n* Enim eveniet perspiciatis et sed nihil nam recusandae aut.\n\n# Maiores quo vitae sunt et iure adipisci quo.\n\n* Cupiditate quis temporibus et maxime perferendis voluptas.\n* Qui rerum minus ut consequuntur nisi.\n* Earum rerum dolorem sunt voluptatibus quos quam.\n\n\\\n\r\n------WebKitFormBoundaryACNFXVX6hMiTZG61\r\nContent-Disposition: form-data; name="resources"\r\n\r\n[object Object]\r\n------WebKitFormBoundaryACNFXVX6hMiTZG61\r\nContent-Disposition: form-data; name="order"\r\n\r\n2\r\n------WebKitFormBoundaryACNFXVX6hMiTZG61\r\nContent-Disposition: form-data; name="can_skip"\r\n\r\n0\r\n------WebKitFormBoundaryACNFXVX6hMiTZG61\r\nContent-Disposition: form-data; name="value"\r\n\r\ntopic/29/molestiae.pdf\r\n------WebKitFormBoundaryACNFXVX6hMiTZG61--\r\n' \
      --compressed

_Issue created from a [Mattermost message](https://mattermost.etd24.pl/_redirect/pl/nys38qcpj7ypfpimncggy8u7dw) *by @victazzz*._

**Comment by dawidzebacki** [comment]
@pa-cholek 
1. Adding test topic with `active: false`, `preview: true`, `can_skip: true`. After request answers these data are: `active: true`, `preview: false`, `can_skip: true`. Editing works properly.

![Zrzut ekranu z 2021-09-22 09-26-21](https://user-images.githubusercontent.com/64470068/134300696-3a6ed3cf-2198-4de3-af16-6a5568bd01d2.png)

![Zrzut ekranu z 2021-09-22 09-21-46](https://user-images.githubusercontent.com/64470068/134300153-32dd6402-15eb-4b89-ab61-81a2b282a748.png

![Zrzut ekranu z 2021-09-22 09-22-04](https://user-images.githubusercontent.com/64470068/134300180-28c99116-bde1-4349-8c19-d31e791988e0.png)
)

@victazzz was that about it?
