### ISSUE TITLE
[LMS Admin] #16 creating new category is not...

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#168]
creating new category is not refreshing the category list

*Source url:* https://awf-adminlms.etd24.pl/#/categories
*Reported by:* mateusz@escolasoft.com
*Reported at:* 27 Sep at 10:59 UTC

*Location:* PL, Pomerania, Gdansk
*Browser:* Chrome 93.0.4577.63

*OS:* macOS 10.15.7
*Screen:* 2048x1152
*Viewport:* 2048x1016

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/b307ykjnw50dx3pg1r2y/zdakg57a8gbzawk7qvm8/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MzI3NDAzNTQsImRhdGEiOnsicmVwb3J0IjoiemRha2c1N2E4Z2J6YXdrN3F2bTgiLCJ1c2VyIjoiR2l0SHViIn19.5AXK_L_ulm4NSsAtZ1Lyui--af-5rNi01D4pdQDcSJY)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/zdakg57a8gbzawk7qvm8](https://ybug.io/dashboard/reports/detail/zdakg57a8gbzawk7qvm8)

**Comment by victazzz** [comment]
it works
