### ISSUE TITLE
create new topics lesson editor

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#204]
based on https://experium.github.io/react-editor/

**Comment by qunabu** [comment]
@mcholcha @dawidzebacki please estimate this task in hours 

replace this 
![image](https://user-images.githubusercontent.com/214608/140732291-8985599a-791e-4303-9d28-2cf8f90a31c8.png)

with this 
![image](https://user-images.githubusercontent.com/214608/140732329-f3292133-3eea-4d3c-8b6a-3e8a31dfb971.png)

* right side panel list of possible topic type 
* sortable 
* adding new content by drag * drop 
* editing should open current edit form in popup (like in demo but different form) current code should be just put there as antd form (no actually no new code is needed for editing form popup) 
* note that this demo is based on ant-desing as well 
* current code should remain there should be just switch to choose which editor you want to

**Comment by dawidzebacki** [comment]
@qunabu our estimation of this issue is around 4 days (~32hours)
