### ISSUE TITLE
assign routes to user permissions 

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#248]
<img width="1325" alt="Screenshot 2021-12-13 at 15 23 35" src="https://user-images.githubusercontent.com/214608/145829617-08c88a33-135a-409c-9e5e-b11daa3d2862.png">

**Comment by qunabu** [comment]
![image](https://user-images.githubusercontent.com/214608/145834180-23fe8bcc-5b7c-45c4-b4d1-bd9b61301d79.png)

**Comment by mcholcha** [comment]
Most of it has been done:
https://github.com/EscolaLMS/Admin/pull/252

[Blocked] Some permissions are missing:
https://github.com/EscolaLMS/API/issues/94
