### ISSUE TITLE
[LMS Admin] #38 Nie można zapisać wartości pola,...

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#268]
Nie można zapisać wartości pola, gdy rules weryfikują pole jako boolean

*Source url:* https://admin-stage.escolalms.com/#/settings/escola_auth
*Reported by:* 
*Reported at:* 30 Dec at 13:20 UTC

*Location:* PL, Lesser Poland, Stary Sacz
*Browser:* Chrome 96.0.4664.110

*OS:* macOS 10.15.7
*Screen:* 1920x1080
*Viewport:* 1920x1001

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/b307ykjnw50dx3pg1r2y/djahjaxcfasg96q2swrb/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NDA4NzA0NjYsImRhdGEiOnsicmVwb3J0IjoiZGphaGpheGNmYXNnOTZxMnN3cmIiLCJ1c2VyIjoiR2l0SHViIn19.WG-QYM5wN9iw8lK42CAUtqbhA0UZlkgtq3JpPfaKbkE)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/djahjaxcfasg96q2swrb](https://ybug.io/dashboard/reports/detail/djahjaxcfasg96q2swrb)

**Comment by victazzz** [comment]
ready for test
