### ISSUE TITLE
[LMS Admin] #39 Nie można wyczyścić wartości dla...

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#269]
Nie można wyczyścić wartości dla pola additional_fields_required

*Source url:* https://admin-stage.escolalms.com/#/settings/escola_auth
*Reported by:* 
*Reported at:* 30 Dec at 14:22 UTC

*Console:* [1× Error](https://ybug.io/dashboard/reports/detail/qvd6naj8y7a4y2p76qn7#console)

*Location:* PL, Lesser Poland, Stary Sacz
*Browser:* Chrome 96.0.4664.110

*OS:* macOS 10.15.7
*Screen:* 1920x1080
*Viewport:* 1920x1001

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/b307ykjnw50dx3pg1r2y/qvd6naj8y7a4y2p76qn7/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NDA4NzQxNTYsImRhdGEiOnsicmVwb3J0IjoicXZkNm5hajh5N2E0eTJwNzZxbjciLCJ1c2VyIjoiR2l0SHViIn19.FCcK5YRaUTO6mR3NMf6eqEQtaAVw2o9Y9jqZ4ReQWqs)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/qvd6naj8y7a4y2p76qn7](https://ybug.io/dashboard/reports/detail/qvd6naj8y7a4y2p76qn7)

**Comment by victazzz** [comment]
ready for test
