### ISSUE TITLE
[LMS Admin] #65 Opcja edycji nie działa. Po...

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#350]
Opcja edycji nie działa. Po kliknięciu przycisku Edytuj nic się nie dzieje. Nie pojawia się pole Edycji i dodawania H5P wewnątrz platformy.

*Source url:* https://admin-stage.escolalms.com/#/courses/15/program
*Reported by:* artur.kobos@escolasoft.com
*Reported at:* 11 Feb at 17:42 UTC

*Location:* PL, Mazovia, Warsaw
*Browser:* Opera 83.0.4254.27

*OS:* Windows 7
*Screen:* 1536x864
*Viewport:* 2244x1191

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/b307ykjnw50dx3pg1r2y/854r9h2gv73byj49hgga/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NDQ2MDEzNzAsImRhdGEiOnsicmVwb3J0IjoiODU0cjloMmd2NzNieWo0OWhnZ2EiLCJ1c2VyIjoiR2l0SHViIn19.PerrDzO5kcOQBrEU9YCryVAytAKLoZjRTfSPNtA0jMs)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/854r9h2gv73byj49hgga](https://ybug.io/dashboard/reports/detail/854r9h2gv73byj49hgga)

**Comment by victazzz** [comment]
disable this edit button if h5p element is not selected
