### ISSUE TITLE
[LMS Admin] #70 on success upload go to h5p edit...

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#375]
on success upload go to h5p edit page

*Source url:* https://admin.sa.etd24.pl/#/h5ps
*Reported by:* mateusz@escolasoft.com
*Reported at:* 09 Mar at 11:35 UTC

*Location:* PL, Pomerania, Gdansk
*Browser:* Chrome 99.0.4844.51

*OS:* macOS 10.15.7
*Screen:* 1728x1117
*Viewport:* 1728x943

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/b307ykjnw50dx3pg1r2y/zff6rv1yrxc68wtf041b/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NDY4MjU3NzAsImRhdGEiOnsicmVwb3J0IjoiemZmNnJ2MXlyeGM2OHd0ZjA0MWIiLCJ1c2VyIjoiR2l0SHViIn19.qrzAog_tOz_HEGrGsY6afzabObCLybP_tC3odMuBnDo)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/zff6rv1yrxc68wtf041b](https://ybug.io/dashboard/reports/detail/zff6rv1yrxc68wtf041b)

**Comment by victazzz** [comment]
when i want to upload h5p i get 500 
![image](https://user-images.githubusercontent.com/24989821/159175635-222afbf8-f157-49a7-b9be-92b7eaccc880.png)
