### ISSUE TITLE
[LMS Admin] #72 dlaczego jest auto uzupełnienie...

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#391]
dlaczego jest auto uzupełnienie pola email i password podczas dodawania nowego użytkownika

wczytało z zapisanego hasła w przeglądarce

(najprawdopodobniej name pola email i password jest taka sama jak przy logowaniu i nie jest wyłączony autocomplit)

*Source url:* https://admin.sa.etd24.pl/#/users/new
*Reported by:* 
*Reported at:* 16 Mar at 09:39 UTC

*Location:* PL, Lesser Poland, Krakow
*Browser:* Firefox 98.0

*OS:* Windows 10.0
*Screen:* 1536x864
*Viewport:* 1536x739

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/b307ykjnw50dx3pg1r2y/nv192gkn8db8zm505wfj/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NDc0MjM2MDcsImRhdGEiOnsicmVwb3J0IjoibnYxOTJna244ZGI4em01MDV3ZmoiLCJ1c2VyIjoiR2l0SHViIn19.RVoc0NphTxWm30ca2MiEGFmtk-bFZoQD9MdG5FnRHmU)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/nv192gkn8db8zm505wfj](https://ybug.io/dashboard/reports/detail/nv192gkn8db8zm505wfj)

**Comment by pieecia** [comment]
@qunabu I couldn't solve the problem, I tried to pass the props `autoComplete="off"` like in the article https://bobbyhadz.com/blog/react-autocomplete-off#turn-off-autocomplete-on-an-input-in-react or this
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

but no luck, browser behavior wins, it seems like a popular problem for many years
