### ISSUE TITLE
[LMS Admin] #82 Pętla w kategorii - Admin panel.

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#486]
Pętla w kategorii - Admin panel.

Kategoria 1 i 11 są sobie nadrzędną i podrzędną. Nie da się ich usunąć.

*Source url:* https://admin-stage.escolalms.com/#/categories
*Reported by:* artur.kobos@escolasoft.com
*Reported at:* 29 Jun at 14:11 UTC

*Location:* PL, Mazovia, Warsaw
*Browser:* Opera 88.0.4412.53

*OS:* Windows 7
*Screen:* 1536x864
*Viewport:* 1870x943

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/b307ykjnw50dx3pg1r2y/99fg9gkhkqr1wxgc4fkt/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTY1MTE5MjQsImRhdGEiOnsicmVwb3J0IjoiOTlmZzlna2hrcXIxd3hnYzRma3QiLCJ1c2VyIjoiR2l0SHViIn19.7YoIOgJSkXKG0qUowFkm8L-7jiqeqMIH1iJh7mRuekk)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/99fg9gkhkqr1wxgc4fkt](https://ybug.io/dashboard/reports/detail/99fg9gkhkqr1wxgc4fkt)

**Comment by pieecia** [comment]
@qunabu I talked to Artur, the task can be closed
