### ISSUE TITLE
[LMS Admin] #83 Admin panel. Przy próbie...

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#487]
Admin panel. Przy próbie wyłączenia czasu i zatwierdzeniu data wciąż powraca i nie da się jej usunąć.

*Source url:* https://admin-stage.escolalms.com/#/courses/7/attributes
*Reported by:* artur.kobos@escolasoft.com
*Reported at:* 29 Jun at 14:32 UTC

*Location:* PL, Mazovia, Warsaw
*Browser:* Opera 88.0.4412.53

*OS:* Windows 7
*Screen:* 1536x864
*Viewport:* 1870x943

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/b307ykjnw50dx3pg1r2y/cwfw2atgn9x4m4z18v8b/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTY1MTMxODMsImRhdGEiOnsicmVwb3J0IjoiY3dmdzJhdGduOXg0bTR6MTh2OGIiLCJ1c2VyIjoiR2l0SHViIn19.LdvZj0ZLXVN9044FxhIreUNgGD6bf0jjpXk3vBdOQeA)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/cwfw2atgn9x4m4z18v8b](https://ybug.io/dashboard/reports/detail/cwfw2atgn9x4m4z18v8b)

**Comment by pieecia** [comment]
@qunabu these fields are mandatory, the validation will show an error that the field is required

**Comment by dyfero** [comment]
These fields are not required https://github.com/EscolaLMS/Courses/blob/main/src/Models/Course.php#L242

null values
```
curl --location --request POST 'https://api-stage.escolalms.com/api/admin/courses/155' \
--header 'accept: application/json' \
--header 'Authorization: Bearer NrQuBlOwhnZW3UZNNdczRqJLzca1MyTEQK8iyLB3sOvetHrrGQ8pKX5FIDfnRIVLShhyjW2TB8dnu4_DQzd1j9FR3iISaxPTkZPlUCXmVqLWPqleJHVj4qTJGkWc2R971x9Kzkfm0xk3Li2wn1YgleHMyAMerRu09tLDQWfBVpcoO45iOzkBgMHBFKUfcQWot_-Q' \
--header 'X-CSRF-TOKEN;' \
--header 'Content-Type: application/json' \
--data-raw '{
    "active_from": null,
    "active_to": null
}'
```
or empty string
```
curl --location --request POST 'https://api-stage.escolalms.com/api/admin/courses/155' \
--header 'accept: application/json' \
--header 'Authorization: Bearer NrQuBlOwhnZW3UZNNdczRqJLzca1MyTEQK8iyLB3sOvetHrrGQ8pKX5FIDfnRIVLShhyjW2TB8dnu4_DQzd1j9FR3iISaxPTkZPlUCXmVqLWPqleJHVj4qTJGkWc2R971x9Kzkfm0xk3Li2wn1YgleHMyAMerRu09tLDQWfBVpcoO45iOzkBgMHBFKUfcQWot_-Q' \
--header 'X-CSRF-TOKEN;' \
--form 'active_from=""' \
--form 'active_to=""'
```

**Comment by qunabu** [comment]
@pieecia ☝️
