### ISSUE TITLE
[LMS Admin] #86 Admin panel - Zmiany statusu się...

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#490]
Admin panel - Zmiany statusu się nie zapisują. Ogólnie jak próbuje coś zmieniać w ustawieniach kursów to system nie zapamiętuje zatwierdzonych zmian.

*Source url:* https://admin-stage.escolalms.com/#/courses/57
*Reported by:* artur.kobos@escolasoft.com
*Reported at:* 30 Jun at 15:06 UTC

*Console:* [2× Log](https://ybug.io/dashboard/reports/detail/x4ryyh2bf0n872sjk4as#console)

*Location:* PL, Mazovia, Warsaw
*Browser:* Opera 88.0.4412.53

*OS:* Windows 7
*Screen:* 1536x864
*Viewport:* 1870x943

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/b307ykjnw50dx3pg1r2y/x4ryyh2bf0n872sjk4as/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTY2MDE1OTcsImRhdGEiOnsicmVwb3J0IjoieDRyeXloMmJmMG44NzJzams0YXMiLCJ1c2VyIjoiR2l0SHViIn19.O4kduhZ8voArIKz4xGgrRKYtXzhy1bdIyFiNLZXfsMM)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/x4ryyh2bf0n872sjk4as](https://ybug.io/dashboard/reports/detail/x4ryyh2bf0n872sjk4as)

**Comment by pieecia** [comment]
@qunabu the form works, you can close issue
