### ISSUE TITLE
[LMS Admin] #90 Admin panel - wyszukiwanie zdjęć...

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#494]
Admin panel - wyszukiwanie zdjęć z plików w dodawaniu ikon do kategorii nie wyświetla plików dodanych do platformy.

*Source url:* https://admin-stage.escolalms.com/#/categories
*Reported by:* artur.kobos@escolasoft.com
*Reported at:* 06 Jul at 10:45 UTC

*Location:* PL, Mazovia, Warsaw
*Browser:* Opera 88.0.4412.53

*OS:* Windows 7
*Screen:* 1536x864
*Viewport:* 2244x1188

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/b307ykjnw50dx3pg1r2y/rzwazq9r9b2asr5m9c2b/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTcxMDQzNDQsImRhdGEiOnsicmVwb3J0Ijoicnp3YXpxOXI5YjJhc3I1bTljMmIiLCJ1c2VyIjoiR2l0SHViIn19.kmsMLumjyhtxqukSs9ZEdKh-M3j72pugZS257dPEDd8)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/rzwazq9r9b2asr5m9c2b](https://ybug.io/dashboard/reports/detail/rzwazq9r9b2asr5m9c2b)

**Comment by pieecia** [comment]
@qunabu just checked it, works

![Zrzut ekranu 2022-10-13 o 16 07 01](https://user-images.githubusercontent.com/8327453/195619500-7bb3bb92-ea06-4076-919c-e50388565a34.png)
![Zrzut ekranu 2022-10-13 o 16 06 55](https://user-images.githubusercontent.com/8327453/195619495-3874fba0-a108-436a-bfb7-6de4b73a4deb.png)
