### ISSUE TITLE
[LMS Admin] #104 Admin panel - Kurs - Ankiety

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#546]
Admin panel - Kurs - Ankiety

Ankiety nie posiadają tutaj tytułów, czyli swoich nazw. Posiadają duplikowany id z wcześniejszym dopiskiem Ankieta. Dobrze byłoby gdyby pojawiały się tutaj nazwy ankiet.

*Source url:* https://admin-stage.escolalms.com/#/courses/list/63/questionnaires
*Reported by:* artur.kobos@escolasoft.com
*Reported at:* 03 Aug at 17:23 UTC

*Location:* PL, Mazovia, Warsaw
*Browser:* Opera 89.0.4447.71

*OS:* Windows 7
*Screen:* 1536x864
*Viewport:* 2244x1084

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/b307ykjnw50dx3pg1r2y/3tthrtga87wvgabsgm3y/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTk1NDc0NDIsImRhdGEiOnsicmVwb3J0IjoiM3R0aHJ0Z2E4N3d2Z2Fic2dtM3kiLCJ1c2VyIjoiR2l0SHViIn19.SYznoOQ270kKihmPFo2vCUp_fEeAtSNkgfaDtZMhOgE)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/3tthrtga87wvgabsgm3y](https://ybug.io/dashboard/reports/detail/3tthrtga87wvgabsgm3y)

**Comment by pieecia** [comment]
@qunabu the problem is solved, you can close

![Zrzut ekranu 2022-09-22 o 12 42 19](https://user-images.githubusercontent.com/8327453/191726619-b48ea79e-7113-4bf1-be5a-95cece43f67f.png)
