### ISSUE TITLE
[LMS Admin] #111 w settings dodac obsluge typu...

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#573]
w settings dodac obsluge typu boolean

*Source url:* https://admin-stage.escolalms.com/#/configuration/settings/hh5p
*Reported by:* mateusz@escolasoft.com
*Reported at:* 01 Sep at 11:05 UTC

*Location:* PL, Pomerania, Rumia
*Browser:* Chrome 104.0.0.0

*OS:* macOS 10.15.7
*Screen:* 1920x1080
*Viewport:* 1920x473

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/b307ykjnw50dx3pg1r2y/csgnhj0d96qhrrrhdsv6/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NjIwMzAzMjYsImRhdGEiOnsicmVwb3J0IjoiY3NnbmhqMGQ5NnFocnJyaGRzdjYiLCJ1c2VyIjoiR2l0SHViIn19.Q62byqSaKHTuCf1TL_Yw783ynuuDah53_zlVTbaA-nc)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/csgnhj0d96qhrrrhdsv6](https://ybug.io/dashboard/reports/detail/csgnhj0d96qhrrrhdsv6)

**Comment by pieecia** [comment]
@qunabu do you mean enable switches in the edit modal? they are now disabled

![Zrzut ekranu 2022-10-13 o 15 49 36](https://user-images.githubusercontent.com/8327453/195615542-dd8d64e8-c277-40ad-938e-4542c73a1dfd.png)

**Comment by qunabu** [comment]
<img width="731" alt="Screenshot 2022-10-14 at 11 21 24" src="https://user-images.githubusercontent.com/214608/195811726-ba9c9f96-ad8f-45f3-9110-089b1fbfdf77.png">
<img width="675" alt="Screenshot 2022-10-14 at 11 20 49" src="https://user-images.githubusercontent.com/214608/195811735-e646023d-d5af-4d90-b3c2-6699c518a40c.png">
