### ISSUE TITLE
[LMS Admin] #112 base price should not be here

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#574]
base price should not be here

*Source url:* https://admin-stage.escolalms.com/#/courses/list/57
*Reported by:* mateusz@escolasoft.com
*Reported at:* 01 Sep at 11:36 UTC

*Location:* PL, Pomerania, Rumia
*Browser:* Chrome 104.0.0.0

*OS:* macOS 10.15.7
*Screen:* 1920x1080
*Viewport:* 1920x918

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/b307ykjnw50dx3pg1r2y/nzj0xskg4fkan4s2bnsj/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NjIwMzIxNjcsImRhdGEiOnsicmVwb3J0IjoibnpqMHhza2c0ZmthbjRzMmJuc2oiLCJ1c2VyIjoiR2l0SHViIn19.lVAgQcI0NinOq5uQ0QO4Es0fJKnH0-PBkRR5Olc0_ZY)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/nzj0xskg4fkan4s2bnsj](https://ybug.io/dashboard/reports/detail/nzj0xskg4fkan4s2bnsj)

**Comment by pieecia** [comment]
![Zrzut ekranu 2022-10-4 o 13 30 27](https://user-images.githubusercontent.com/8327453/193809092-ee5416e8-486c-4b6f-b92b-0f1b1e3d0088.png)

@qunabu in which section should be? I couldn't find this input in figma

![Zrzut ekranu 2022-10-4 o 13 30 27](https://user-images.githubusercontent.com/8327453/193809344-567bd272-2f46-477a-9299-8e700ad6ab79.png)

**Comment by qunabu** [comment]
price should only be in "prices" not in attribute 
proce should be related to products only (prices tab is shortcut to products)

**Comment by qunabu** [comment]
maybe i was looking at old/cached version of the admin panel, this issue might be resolved already

**Comment by pieecia** [comment]
in the "product" tab, we already have inputs with the price

![Zrzut ekranu 2022-10-4 o 13 49 03](https://user-images.githubusercontent.com/8327453/193812174-a0ecc132-dfb4-46ba-9342-d5dba9361466.png)

**Comment by qunabu** [comment]
in product is ok, in attributes not

**Comment by qunabu** [comment]
just tested an price is still there - should be removed 
![Uploading Screenshot 2022-10-04 at 13.55.08.png…]()
