### ISSUE TITLE
h5p export 

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#626]
https://admin-stage.escolalms.com/#/courses/h5ps

export button doesn't work 
<img width="759" alt="image" src="https://user-images.githubusercontent.com/214608/195097539-aff64172-e89d-4a7a-8736-604603426133.png">

missing bearer token in sending form 
* it can';t be a url link must be a form to send a bearer token

**Comment by qunabu** [comment]
<img width="325" alt="image" src="https://user-images.githubusercontent.com/214608/195099090-20058a8f-f754-4a45-8833-45ffe1c12779.png">

**Comment by pieecia** [comment]
@qunabu it should be closed https://github.com/EscolaLMS/Admin/pull/627
