### ISSUE TITLE
pages section

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#70]
- [x] list of pages (paginated but this might not be implemented yet)
- [x] add new page (new page in admin)  
- [x] edit page 
- [x] delete page 
- [x] search pages in header (like courses, orders, payments etc, might not be implemented) 

if something is blocked by backend ask @pa-cholek for implementation

**Comment by qunabu** [comment]
blocked by https://github.com/EscolaLMS/pages/issues/20

**Comment by qunabu** [comment]
![image](https://user-images.githubusercontent.com/214608/133235722-976aa6e0-398e-4343-af91-2ff8610f3cad.png)

**Comment by pa-cholek** [comment]
Use PATCH instead of PUT? Swagger has this endpoint as PATCH too.
But then again, it probably should be a PUT because it has no optional fields...

**Comment by qunabu** [comment]
I'll amend admin and adapt to backend

**Comment by qunabu** [comment]
replace `PUT` with `PATCH` https://github.com/EscolaLMS/Admin/blob/master/src/services/escola-lms/pages.ts#L47

**Comment by dawidzebacki** [comment]
https://github.com/EscolaLMS/Admin/pull/128
