### ISSUE TITLE
add caching for GET requests

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#78]
https://github.com/umijs/umi-request#request-options

**Comment by dawidzebacki** [comment]
errors for caching users in courses -> edit course (UserSelect) component, added exception for caching in this component

![Zrzut ekranu z 2021-09-15 16-15-55](https://user-images.githubusercontent.com/64470068/133450265-ed203399-6aa0-4da9-bf35-c94f0795edc4.png)
![Zrzut ekranu z 2021-09-15 16-14-30](https://user-images.githubusercontent.com/64470068/133450215-f0ad9882-2e85-4904-b610-d49aa2ef944c.png)

errors for caching files in files -> change to some directory and try comeback

![Zrzut ekranu z 2021-09-15 16-15-55](https://user-images.githubusercontent.com/64470068/133450265-ed203399-6aa0-4da9-bf35-c94f0795edc4.png)

function fetchFiles in FilesBrowser component (index.tsx:78) causing same error as before, added exception for not caching files for now

**Comment by dawidzebacki** [comment]
closing with 2 exceptions for now
