### ISSUE TITLE
Error when creating user

### ISSUE THREAD

**Issue by Y0p11** [EscolaLMS/Admin#783]
Hello !

I installed Wellms via the Create-LMS-App script.  

When I try to create a new user, I get an error : `The return URL field is required`.  
I get the same error going through the Swagger, but the error does not occur on your demo instance. 

I guess I'm missing an environment variable, but can't figure out which one.
![Snapshot_2023-04-18_18-57-17](https://user-images.githubusercontent.com/77102322/232745181-f922ce70-497d-409f-89d6-c2440cd4603e.png)

**Comment by mako321** [comment]
Hi! 
Please check your settings tab in the admin panel. The `return_url` variable should be set to the front application. See the image below. This variable is used in the account activation email.

![Zrzut ekranu 2023-04-18 o 12 11 55](https://user-images.githubusercontent.com/59456825/232746972-ac5256e3-1f6e-45bf-8ae7-34aadf57302e.png)

**Comment by qunabu** [comment]
https://github.com/EscolaLMS/documentation/blob/main/docs/src/app-guide/auth.md would you possible describe this issue in the documentation?

**Comment by qunabu** [comment]
Correct file to update https://github.com/EscolaLMS/Auth/blob/main/ADMIN.md
