### ISSUE TITLE
i18n flags and missing transaltions

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#81]
example here https://preview.pro.ant.design/dashboard/analysis
![image](https://user-images.githubusercontent.com/214608/131147448-02011cb7-0ed0-436e-91e8-618b415086ac.png)

**Comment by dawidzebacki** [comment]
added flags and translations for now, not closing yet because later there will be need to:

- check all flags when project will grow
- add proper translations for pl-PL and en-US files

**Comment by qunabu** [comment]
testing here https://escolalms.github.io/Admin/#/Admin/users 

<img width="259" alt="Screenshot 2021-09-08 at 09 32 51" src="https://user-images.githubusercontent.com/214608/132466122-d61faaac-f5ed-4814-8ec3-e1a154c9d956.png">

- [ ] remove chineese stuff 
- [ ] add proper PL flag 
- [ ] remove help icon 
- [ ] remove search bar
