### ISSUE TITLE
json viewer

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#98]
add json viewer in 2 places

- [x]  settings json preview 
- [x]  xapi h5p preview 

https://www.npmjs.com/package/react-json-view

**Comment by qunabu** [comment]
<img width="981" alt="Screenshot 2021-09-14 at 08 33 48" src="https://user-images.githubusercontent.com/214608/133207172-5d38b459-a88b-4a93-8db2-58ccd2c8d84e.png">
<img width="1144" alt="Screenshot 2021-09-14 at 08 34 18" src="https://user-images.githubusercontent.com/214608/133207187-58492119-6d3c-4314-affc-f1451a0cd6eb.png">

**Comment by dawidzebacki** [comment]
https://github.com/EscolaLMS/Admin/pull/142
