### ISSUE TITLE
testing here https://escolalms.github.io/Admin/#/Admin/users

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Admin#99]
testing here https://escolalms.github.io/Admin/#/Admin/users 

<img width="259" alt="Screenshot 2021-09-08 at 09 32 51" src="https://user-images.githubusercontent.com/214608/132466122-d61faaac-f5ed-4814-8ec3-e1a154c9d956.png">

- [ ] remove chineese stuff 
- [ ] add proper PL flag 
- [x] remove help icon 
- [x] remove search bar

_Originally posted by @qunabu in https://github.com/EscolaLMS/Admin/issues/81#issuecomment-914993792_

**Comment by dawidzebacki** [comment]
- searchbar deleted
- help icon deleted

- added contribute to umi for polish flag, text and custom icon
https://github.com/umijs/plugins/pull/708
